FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    iproute2 \
    iputils-ping \
    curl \
    dnsutils \
    net-tools \
    traceroute \
    tcpdump \
    vim \
    less \
    procps \
    python3 \
    python3-pip \
    telnet \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
